### ISSUE TITLE
Looks like not working with new version of SourceTree any more

### ISSUE THREAD

**Issue by chrisspiegl** [zhaocai/alfred2-sourcetree-workflow#6]
I was using this workflow about a year or two ago and it worked like a charm. Now I am back in code and wanted to use it again but it looks like it's no longer working.

Any plans to make this compatible with the current version of SourceTree?

Thanks

**Comment by kaspersoerensen** [comment]
Hi @spieglio 
I think you need to be a bit more specific. I am running the workflow with no issues.

Can you explain what goes wrong?

**Comment by chrisspiegl** [comment]
I found an update to my version a couple days after this message. Fixed it and I am using it again. Don't know what went wrong there. Sorry.
