### ISSUE TITLE
Workflow no longer working with Alfred 3

### ISSUE THREAD

**Issue by justinjm** [zhaocai/alfred2-sourcetree-workflow#7]
Hi @zhaocai, Love this alfred worklow and it's been instrumental in my daily work for the past couple years! Until last week, when it stopped working for me (when I updated to macOS High Sierra). Reaching out in the hopes it's a user error/something I'm overlooking (especially since I'm on Alfred 3) since I'm not sure if this workflow/repo is being maintained still? Thank you in advance for any help! :)

## Issue Summary

The Sourcetree Alfred workflow no longer works when running `st` or `stbookmark`. 

## Steps to reproduce

Running the command `st` in Alfred yields no bookmarks or data about sourcetree:

![](http://d.pr/i/omp9Oi+)

and here's the debug log: 

```
[2017-12-08 10:19:51][input.scriptfilter] Queuing argument ''
[2017-12-08 10:19:51][input.scriptfilter] Script with argument '(null)' finished
[2017-12-08 10:19:51][ERROR: input.scriptfilter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- alfred (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./main.rb:20:in `<main>'
```

## System Info

- Alfred 3.5.1
- Sourcetree 2.7 (143)
- macOS High Sierra 10.13.2

**Comment by tony0x59** [comment]
same issue

**Comment by tony0x59** [comment]
okay, I solved it~ 

open workflow path, and into "./bundle/ruby" (like that: /Users/tony/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.118F73F2-30F3-4D31-A3DB-E5B594588D53/bundle/ruby)

run command:
```
$ ln -s "`pwd`/2.0.0" "`pwd`/2.3.0"
```

**Comment by justinjm** [comment]
@tony0x59 this worked perfectly and solved my issue, thank you! :)

**Comment by justinjm** [comment]
@tony0x59 I'm encountering a similar [issue as before](https://github.com/zhaocai/alfred2-sourcetree-workflow/issues/7#issue-280525344), not sure if due to upgrading Alfred, Sourcetree or both. Are you experiencing the same issue or is there an issue on my side? 

Thank you in advance for any help!
Justin

## Issue Summary

The Sourcetree Alfred workflow no longer works when running `st` 

## Steps to reproduce

Running the command `st` in Alfred yields no bookmarks or data about sourcetree:


## Alfred debug log

```
[2018-06-13 11:26:15][ERROR: input.scriptfilter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- alfred (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./main.rb:20:in `<main>'
```

## System Info

- Alfred: v3.6.1 [910]
- Sourcetree: 2.7.3 (169)
- macOS High Sierra 10.13.5

**Comment by janek** [comment]
@justinjm I had the same problem, with Alfred v3.6.1 and SourceTree v2.7.6  (both newest at the time of writing). The solution that @tony0x59 came up with works for me.

**Comment by MattFoley** [comment]
Still working!

**Comment by justinjm** [comment]
@janekszynal thanks for the feedback! I _finally_ realized my issue was from syncing settings across multiple macs with different versions of SourceTree. Closing this out since @tony0x59's solution still solves this

**Comment by isaced** [comment]
> okay, I solved it~
> 
> open workflow path, and into "./bundle/ruby" (like that: /Users/tony/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.118F73F2-30F3-4D31-A3DB-E5B594588D53/bundle/ruby)
> 
> run command:
> 
> ```
> $ ln -s "`pwd`/2.0.0" "`pwd`/2.3.0"
> ```

work for me, but i need change `2.3.0` to my local ruby version.

```
ln -s "`pwd`/2.0.0" "`pwd`/2.6.0"
```
